### ISSUE TITLE
The problem about data provided by you

### ISSUE THREAD

**Issue by JonnesLin** [shlizee/Audeo#2]
Hi, thanks for your sharing! But I have a problem with the data. The input_images just has 5 images and are you sure it is right?

**Comment by DragonLiu1995** [comment]
We input 5 consecutive frames of piano keyboard and predict the pressed keys in the middle frame.

**Comment by JonnesLin** [comment]
So you mean these 5 photos are just used for testing rather than training? Could you provide some training data?

**Comment by DragonLiu1995** [comment]
Both training & testing use 5 frames. For data, you could download the Youtube video from Paul Barton, and process the video into consecutive frames of images, and use the piano keyboard locations specified in piano_coords.py to crop the keyboard part.

**Comment by sukun1045** [comment]
@JonnesLin Hi, thank you for your interests. I guess there is confusion here. To predict the key pressed at time t, we provide the grey images at time t-2, t-1, t, t+1, t+2, and stack them as one single input. This strategy is used in both training and testing. Since the data is from Youtube and we don't have the right to release them here, we won't be able to provide the training data directly. In Google Drive, **input_images** are only examples of how the images data should look like. You would have to preprocess the videos yourself and cropped the images.

**Comment by JonnesLin** [comment]
> @JonnesLin Hi, thank you for your interests. I guess there is confusion here. To predict the key pressed at time t, we provide the grey images at time t-2, t-1, t, t+1, t+2, and stack them as one single input. This strategy is used in both training and testing. Since the data is from Youtube and we don't have the right to release them here, we won't be able to provide the training data directly. In Google Drive, **input_images** are only examples of how the images data should look like. You would have to preprocess the videos yourself and cropped the images.

Thank you for your response!
